/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-11-14T14:38:17.564999600+09:00[Asia/Tokyo]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "dronePortReservation", description = "the dronePortReservation API")
public interface DronePortReservationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /dronePortReservation : ドローンポート予約情報の詳細情報を取得する。
     *
     * @param dronePortReservationId ドローンポート予約を一意に識別するID (required)
     * @return 成功 (status code 200)
     *         or エラー詳細を返却する。 (status code 400)
     *         or エラー詳細を返却する。 (status code 500)
     */
    @Operation(
        operationId = "dronePortReservationGet",
        summary = "ドローンポート予約情報の詳細情報を取得する。"
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/dronePortReservation",
        produces = { "application/json" }
    )
    
    ResponseEntity<Object> dronePortReservationGet(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @NotNull @Parameter(name = "dronePortReservationId", description = "ドローンポート予約を一意に識別するID", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "dronePortReservationId", required = true) UUID dronePortReservationId
    ); 

}
