/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.ouranos.application.digiline.controller;

import net.ouranos.domain.digiline.model.NearMissInformationRequest;
import net.ouranos.domain.digiline.model.NearMissInformationResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-01-24T15:55:05.483153+09:00[Asia/Tokyo]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "NearMissInformation", description = "ヒヤリハット情報の取得API")
public interface NearMissInformationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /nearMissInformation : ヒヤリハット情報の取得
     *
     * @param nearMissInformationRequest  (required)
     * @return 正常終了 (status code 200)
     *         or リクエストが不正です (status code 400)
     *         or 指定した条件にあうヒヤリハット情報が見つかりません (status code 404)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "nearMissInformationPost",
        summary = "ヒヤリハット情報の取得",
        tags = { "NearMissInformation" }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/nearMissInformation",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Object> nearMissInformationPost(@Parameter(name = "X-Tracking", description = "トラッキングID", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tracking", required = false) UUID xTracking,
        @Parameter(name = "NearMissInformationRequest", description = "", required = true) @Valid @RequestBody NearMissInformationRequest nearMissInformationRequest
    ); 

}
